---
title: "About this workshop"
description: |
  Here is how the BYOD R workshop will work
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


The plan is to run weekly lunch time "code club" sessions, just for an hour or so over the next few weeks to help you get your head around what R is useful for and how you might use it with YOUR data. 

I ran a workshop at the AIMOS conference in Melbourne last year and the goal would be to cover the same kind of thing. 
- why you might want to use R
- how to get data into R and cleaned up a bit
- how to get summary stats
- how to use the power of R to visualise your data

I think there will be at least 3 sessions but we will play it by ear a little. 

Often with R training workshops they have you working with beautifully clean sample data, and  that makes it tough when you get back to your lab and discover that your data is not at all behaving in the same way. In these sessions, we will go SUPER SLOW and have you working with your OWN data (if you already have it), so that we don't run into generalisation problems (hopefully). 

We will start in Week 2, on Thursdays at 1pm. Access via zoom...

https://unsw.zoom.us/j/99976541554  